In [72]:
import pandas as pd
from dotenv import load_dotenv
import os
import json

In [75]:
load_dotenv(".env.convert_xlsx_csv") # load variables from .env.convert_xlsx_csv file

INPUT_FILES = json.loads(os.getenv("INPUT_FILES","[]")) # get input files from environment variable
OUTPUT_FILES = json.loads(os.getenv("OUTPUT_FILES","[]")) # get output files from environment variable

python-dotenv could not parse statement starting at line 1
python-dotenv could not parse statement starting at line 2

In [76]:
INPUT_FILES

['https://s3.eu-west-1.amazonaws.com/course.oc-static.com/projects/922_Data+Engineer/922_P8/Weather+Underground+-+Ichtegem%2C+BE.xlsx',
 'https://s3.eu-west-1.amazonaws.com/course.oc-static.com/projects/922_Data+Engineer/922_P8/Weather+Underground+-+La+Madeleine%2C+FR.xlsx']

In [77]:
OUTPUT_FILES

['Weather_Underground_Ichtegem_BE.csv',
 'Weather_Underground_La_Madeleine_FR.csv']

In [80]:
for files in zip(INPUT_FILES,OUTPUT_FILES):
    print(files)

('https://s3.eu-west-1.amazonaws.com/course.oc-static.com/projects/922_Data+Engineer/922_P8/Weather+Underground+-+Ichtegem%2C+BE.xlsx', 'Weather_Underground_Ichtegem_BE.csv')
('https://s3.eu-west-1.amazonaws.com/course.oc-static.com/projects/922_Data+Engineer/922_P8/Weather+Underground+-+La+Madeleine%2C+FR.xlsx', 'Weather_Underground_La_Madeleine_FR.csv')

In [47]:
INPUT_FILE = "https://s3.eu-west-1.amazonaws.com/course.oc-static.com/projects/922_Data+Engineer/922_P8/Weather+Underground+-+Ichtegem%2C+BE.xlsx"
OUTPUT_FILE = "Weather_Underground_Ichtegem_BE.csv"

In [48]:
sheets = pd.read_excel(INPUT_FILE,sheet_name=None)

In [49]:
sheets.items()

dict_items([('011024',          Time Temperature Dew Point Humidity   Wind     Speed      Gust  \
0         NaN         NaN       NaN      NaN    NaN       NaN       NaN
1    00:04:00     56.8 °F   53.1 °F     87 %    WSW   8.2 mph  10.4 mph
2    00:09:00     56.8 °F   52.9 °F     87 %    WSW   7.9 mph   9.8 mph
3    00:14:00     57.0 °F   52.8 °F     86 %   West  10.3 mph  12.8 mph
4    00:19:00     57.2 °F   52.7 °F     85 %    WSW   9.7 mph  12.2 mph
..        ...         ...       ...      ...    ...       ...       ...
284  23:39:00     51.1 °F   50.0 °F     96 %  South   2.1 mph   2.8 mph
285  23:44:00     51.3 °F   50.2 °F     96 %  South   1.7 mph   2.4 mph
286  23:49:00     51.3 °F   50.2 °F     96 %  South   1.6 mph   2.3 mph
287  23:54:00     51.3 °F   50.4 °F     96 %  South   2.2 mph   3.0 mph
288  23:59:00     51.3 °F   50.2 °F     96 %  South   2.0 mph   2.8 mph

     Pressure Precip. Rate. Precip. Accum.   UV   Solar
0         NaN           NaN            NaN  NaN     NaN
1    29.48 in       0.00 in        0.00 in  0.0  0 w/m²
2    29.47 in       0.00 in        0.00 in  0.0  0 w/m²
3    29.47 in       0.00 in        0.00 in  0.0  0 w/m²
4    29.47 in       0.00 in        0.00 in  0.0  0 w/m²
..        ...           ...            ...  ...     ...
284  29.45 in       0.00 in        0.18 in  0.0  0 w/m²
285  29.45 in       0.00 in        0.18 in  0.0  0 w/m²
286  29.46 in       0.00 in        0.18 in  0.0  0 w/m²
287  29.45 in       0.00 in        0.18 in  0.0  0 w/m²
288  29.46 in       0.00 in        0.18 in  0.0  0 w/m²

[289 rows x 12 columns]), ('021024',          Time Temperature Dew Point Humidity   Wind    Speed     Gust  \
0         NaN         NaN       NaN      NaN    NaN      NaN      NaN
1    00:04:00     51.2 °F   50.2 °F     96 %  South  1.4 mph  1.9 mph
2    00:09:00     51.1 °F   50.3 °F     97 %  South  1.0 mph  1.5 mph
3    00:14:00     51.0 °F   50.0 °F     96 %  South  1.0 mph  1.7 mph
4    00:19:00     50.7 °F   50.0 °F     97 %  South  1.1 mph  1.5 mph
..        ...         ...       ...      ...    ...      ...      ...
281  23:39:00     53.1 °F   48.4 °F     84 %     NE  4.5 mph  6.0 mph
282  23:44:00     52.9 °F   48.2 °F     84 %     NE  4.5 mph  5.9 mph
283  23:49:00     52.9 °F   48.3 °F     84 %     NE  3.6 mph  5.0 mph
284  23:54:00     52.9 °F   48.3 °F     84 %    NNE  5.8 mph  7.8 mph
285  23:59:00     52.9 °F   48.5 °F     85 %    NNE  3.7 mph  5.2 mph

     Pressure Precip. Rate. Precip. Accum.   UV   Solar
0         NaN           NaN            NaN  NaN     NaN
1    29.46 in       0.00 in        0.00 in  0.0  0 w/m²
2    29.46 in       0.00 in        0.00 in  0.0  0 w/m²
3    29.47 in       0.00 in        0.00 in  0.0  0 w/m²
4    29.47 in       0.00 in        0.00 in  0.0  0 w/m²
..        ...           ...            ...  ...     ...
281  29.79 in       0.00 in        0.01 in  0.0  0 w/m²
282  29.80 in       0.00 in        0.01 in  0.0  0 w/m²
283  29.80 in       0.00 in        0.01 in  0.0  0 w/m²
284  29.80 in       0.00 in        0.01 in  0.0  0 w/m²
285  29.80 in       0.00 in        0.01 in  0.0  0 w/m²

[286 rows x 12 columns]), ('031024',          Time Temperature Dew Point Humidity Wind    Speed     Gust  Pressure  \
0         NaN         NaN       NaN      NaN  NaN      NaN      NaN       NaN
1    00:04:00     52.8 °F   48.5 °F     85 %  NNE  4.6 mph  6.1 mph  29.80 in
2    00:09:00     52.7 °F   48.4 °F     85 %   NE  4.4 mph  6.3 mph  29.80 in
3    00:14:00     52.8 °F   48.5 °F     85 %   NE  4.8 mph  6.6 mph  29.81 in
4    00:19:00     52.7 °F   48.4 °F     85 %   NE  4.2 mph  5.9 mph  29.80 in
..        ...         ...       ...      ...  ...      ...      ...       ...
280  23:39:00     41.7 °F   40.3 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in
281  23:44:00     41.5 °F   40.1 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in
282  23:49:00     41.5 °F   40.1 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in
283  23:54:00     41.4 °F   40.0 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in
284  23:59:00     41.3 °F   39.8 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in

    Precip. Rate. Precip. Accum.   UV   Solar
0             NaN            NaN  NaN     NaN
1         0.00 in        0.00 in  0.0  0 w/m²
2         0.00 in        0.00 in  0.0  0 w/m²
3         0.00 in        0.00 in  0.0  0 w/m²
4         0.00 in        0.00 in  0.0  0 w/m²
..            ...            ...  ...     ...
280       0.00 in        0.00 in  0.0  0 w/m²
281       0.00 in        0.00 in  0.0  0 w/m²
282       0.00 in        0.00 in  0.0  0 w/m²
283       0.00 in        0.00 in  0.0  0 w/m²
284       0.00 in        0.00 in  0.0  0 w/m²

[285 rows x 12 columns]), ('041024',          Time Temperature Dew Point Humidity Wind    Speed     Gust  Pressure  \
0         NaN         NaN       NaN      NaN  NaN      NaN      NaN       NaN
1    00:04:00     41.0 °F   39.6 °F     95 %  WNW  0.0 mph  0.0 mph  29.95 in
2    00:09:00     40.9 °F   39.5 °F     95 %  WNW  0.0 mph  0.0 mph  29.96 in
3    00:14:00     41.3 °F   39.8 °F     95 %  WNW  0.0 mph  0.0 mph  29.96 in
4    00:19:00     41.3 °F   39.8 °F     95 %  WNW  0.0 mph  0.0 mph  29.96 in
..        ...         ...       ...      ...  ...      ...      ...       ...
284  23:39:00     42.9 °F   42.0 °F     96 %  SSW  0.0 mph  0.0 mph  29.94 in
285  23:44:00     42.9 °F   41.7 °F     96 %  SSW  0.0 mph  0.0 mph  29.94 in
286  23:49:00     42.4 °F   40.9 °F     95 %  SSW  0.0 mph  0.0 mph  29.95 in
287  23:54:00     42.0 °F   40.5 °F     95 %  SSW  0.0 mph  0.0 mph  29.94 in
288  23:59:00     41.4 °F   40.1 °F     95 %  SSW  0.0 mph  0.0 mph  29.94 in

    Precip. Rate. Precip. Accum.   UV   Solar
0             NaN            NaN  NaN     NaN
1         0.00 in        0.00 in  0.0  0 w/m²
2         0.00 in        0.00 in  0.0  0 w/m²
3         0.00 in        0.00 in  0.0  0 w/m²
4         0.00 in        0.00 in  0.0  0 w/m²
..            ...            ...  ...     ...
284       0.00 in        0.00 in  0.0  0 w/m²
285       0.00 in        0.00 in  0.0  0 w/m²
286       0.00 in        0.00 in  0.0  0 w/m²
287       0.00 in        0.00 in  0.0  0 w/m²
288       0.00 in        0.00 in  0.0  0 w/m²

[289 rows x 12 columns]), ('051024',          Time Temperature Dew Point Humidity   Wind    Speed     Gust  \
0         NaN         NaN       NaN      NaN    NaN      NaN      NaN
1    00:04:00     41.7 °F   40.8 °F     96 %    SSW  0.0 mph  0.0 mph
2    00:09:00     42.2 °F   41.3 °F     96 %    SSW  0.0 mph  0.0 mph
3    00:14:00     42.1 °F   41.2 °F     96 %    SSW  0.0 mph  0.0 mph
4    00:19:00     42.4 °F   41.5 °F     96 %    SSW  0.0 mph  0.0 mph
..        ...         ...       ...      ...    ...      ...      ...
284  23:39:00     48.2 °F   43.5 °F     84 %  South  1.4 mph  2.1 mph
285  23:44:00     48.0 °F   43.3 °F     84 %    SSW  1.6 mph  2.2 mph
286  23:49:00     48.0 °F   43.3 °F     84 %  South  1.9 mph  2.6 mph
287  23:54:00     47.8 °F   43.4 °F     85 %  South  1.7 mph  2.3 mph
288  23:59:00     47.7 °F   43.3 °F     85 %  South  1.8 mph  2.5 mph

     Pressure Precip. Rate. Precip. Accum.   UV   Solar
0         NaN           NaN            NaN  NaN     NaN
1    29.94 in       0.00 in        0.00 in  0.0  0 w/m²
2    29.94 in       0.00 in        0.00 in  0.0  0 w/m²
3    29.94 in       0.00 in        0.00 in  0.0  0 w/m²
4    29.94 in       0.00 in        0.00 in  0.0  0 w/m²
..        ...           ...            ...  ...     ...
284  29.68 in       0.00 in        0.01 in  0.0  0 w/m²
285  29.68 in       0.00 in        0.01 in  0.0  0 w/m²
286  29.68 in       0.00 in        0.01 in  0.0  0 w/m²
287  29.68 in       0.00 in        0.01 in  0.0  0 w/m²
288  29.68 in       0.00 in        0.01 in  0.0  0 w/m²

[289 rows x 12 columns]), ('061024',          Time Temperature Dew Point Humidity   Wind    Speed     Gust  \
0         NaN         NaN       NaN      NaN    NaN      NaN      NaN
1    00:04:00     47.5 °F   43.3 °F     85 %  South  1.5 mph  2.3 mph
2    00:09:00     47.3 °F   43.3 °F     86 %  South  2.2 mph  3.1 mph
3    00:14:00     47.3 °F   43.3 °F     86 %  South  1.9 mph  2.6 mph
4    00:19:00     47.2 °F   43.3 °F     86 %  South  1.5 mph  2.3 mph
..        ...         ...       ...      ...    ...      ...      ...
284  23:39:00     57.5 °F   56.4 °F     96 %     SW  1.8 mph  2.9 mph
285  23:44:00     57.6 °F   56.5 °F     96 %     SW  2.2 mph  3.2 mph
286  23:49:00     57.6 °F   56.5 °F     96 %     SW  1.8 mph  2.7 mph
287  23:54:00     57.6 °F   56.5 °F     96 %    SSW  2.4 mph  3.8 mph
288  23:59:00     57.7 °F   56.7 °F     96 %    SSW  2.0 mph  3.2 mph

     Pressure Precip. Rate. Precip. Accum.   UV   Solar
0         NaN           NaN            NaN  NaN     NaN
1    29.68 in       0.00 in        0.00 in  0.0  0 w/m²
2    29.67 in       0.00 in        0.00 in  0.0  0 w/m²
3    29.67 in       0.00 in        0.00 in  0.0  0 w/m²
4    29.67 in       0.00 in        0.00 in  0.0  0 w/m²
..        ...           ...            ...  ...     ...
284  29.28 in       0.00 in        0.09 in  0.0  0 w/m²
285  29.27 in       0.00 in        0.09 in  0.0  0 w/m²
286  29.27 in       0.00 in        0.09 in  0.0  0 w/m²
287  29.28 in       0.00 in        0.09 in  0.0  0 w/m²
288  29.28 in       0.00 in        0.09 in  0.0  0 w/m²

[289 rows x 12 columns]), ('071024',          Time Temperature Dew Point Humidity  Wind    Speed     Gust  \
0         NaN         NaN       NaN      NaN   NaN      NaN      NaN
1    00:04:00     57.7 °F   56.7 °F     96 %    SW  2.4 mph  3.5 mph
2    00:09:00     57.7 °F   56.7 °F     96 %    SW  2.0 mph  2.9 mph
3    00:14:00     57.8 °F   56.8 °F     96 %   WSW  2.5 mph  3.3 mph
4    00:19:00     58.0 °F   56.9 °F     96 %   WSW  3.0 mph  4.0 mph
..        ...         ...       ...      ...   ...      ...      ...
174  14:29:00     65.2 °F   56.3 °F     73 %   WSW  3.7 mph  4.8 mph
175  14:34:00     65.5 °F   56.3 °F     72 %   WSW  3.4 mph  4.2 mph
176  14:39:00     65.7 °F   55.5 °F     70 %   WSW  4.3 mph  6.1 mph
177  14:44:00     66.4 °F   56.1 °F     70 %  West  2.9 mph  4.1 mph
178  14:49:00     66.4 °F   55.7 °F     68 %   WSW  2.7 mph  4.2 mph

     Pressure Precip. Rate. Precip. Accum.   UV       Solar
0         NaN           NaN            NaN  NaN         NaN
1    29.27 in       0.00 in        0.00 in  0.0      0 w/m²
2    29.28 in       0.00 in        0.00 in  0.0      0 w/m²
3    29.28 in       0.00 in        0.00 in  0.0      0 w/m²
4    29.28 in       0.00 in        0.00 in  0.0      0 w/m²
..        ...           ...            ...  ...         ...
174  29.37 in       0.00 in        0.01 in  4.0  414.8 w/m²
175  29.36 in       0.00 in        0.01 in  4.0  416.6 w/m²
176  29.36 in       0.00 in        0.01 in  3.0  338.5 w/m²
177  29.36 in       0.00 in        0.01 in  3.0  349.6 w/m²
178  29.36 in       0.00 in        0.01 in  3.0  345.7 w/m²

[179 rows x 12 columns])])

In [50]:
frames = []
for tab_name, df in sheets.items():
    df["tab_name"] = tab_name          
    frames.append(df)

In [51]:
result = pd.concat(frames, ignore_index=True)

In [52]:
result.head()

,Time,Temperature,Dew Point,Humidity,Wind,Speed,Gust,Pressure,Precip. Rate.,Precip. Accum.,UV,Solar,tab_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,011024
1,00:04:00,56.8 °F,53.1 °F,87 %,WSW,8.2 mph,10.4 mph,29.48 in,0.00 in,0.00 in,0.0,0 w/m²,011024
2,00:09:00,56.8 °F,52.9 °F,87 %,WSW,7.9 mph,9.8 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024
3,00:14:00,57.0 °F,52.8 °F,86 %,West,10.3 mph,12.8 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024
4,00:19:00,57.2 °F,52.7 °F,85 %,WSW,9.7 mph,12.2 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024

In [53]:
result["Date"] = pd.to_datetime(result["tab_name"], format="%d%m%y")

In [54]:
result

,Time,Temperature,Dew Point,Humidity,Wind,Speed,Gust,Pressure,Precip. Rate.,Precip. Accum.,UV,Solar,tab_name,Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,011024,2024-10-01
1,00:04:00,56.8 °F,53.1 °F,87 %,WSW,8.2 mph,10.4 mph,29.48 in,0.00 in,0.00 in,0.0,0 w/m²,011024,2024-10-01
2,00:09:00,56.8 °F,52.9 °F,87 %,WSW,7.9 mph,9.8 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024,2024-10-01
3,00:14:00,57.0 °F,52.8 °F,86 %,West,10.3 mph,12.8 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024,2024-10-01
4,00:19:00,57.2 °F,52.7 °F,85 %,WSW,9.7 mph,12.2 mph,29.47 in,0.00 in,0.00 in,0.0,0 w/m²,011024,2024-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,14:29:00,65.2 °F,56.3 °F,73 %,WSW,3.7 mph,4.8 mph,29.37 in,0.00 in,0.01 in,4.0,414.8 w/m²,071024,2024-10-07
1902,14:34:00,65.5 °F,56.3 °F,72 %,WSW,3.4 mph,4.2 mph,29.36 in,0.00 in,0.01 in,4.0,416.6 w/m²,071024,2024-10-07
1903,14:39:00,65.7 °F,55.5 °F,70 %,WSW,4.3 mph,6.1 mph,29.36 in,0.00 in,0.01 in,3.0,338.5 w/m²,071024,2024-10-07
1904,14:44:00,66.4 °F,56.1 °F,70 %,West,2.9 mph,4.1 mph,29.36 in,0.00 in,0.01 in,3.0,349.6 w/m²,071024,2024-10-07
1905,14:49:00,66.4 °F,55.7 °F,68 %,WSW,2.7 mph,4.2 mph,29.36 in,0.00 in,0.01 in,3.0,345.7 w/m²,071024,2024-10-07

In [55]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1906 entries, 0 to 1905
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Time            1899 non-null   object
 1   Temperature     1899 non-null   object
 2   Dew Point       1899 non-null   object
 3   Humidity        1899 non-null   object
 4   Wind            1892 non-null   object
 5   Speed           1899 non-null   object
 6   Gust            1899 non-null   object
 7   Pressure        1899 non-null   object
 8   Precip. Rate.   1899 non-null   object
 9   Precip. Accum.  1899 non-null   object
 10  UV              1899 non-null   float64
 11  Solar           1899 non-null   object
 12  tab_name        1906 non-null   object
 13  Date            1906 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(12)
memory usage: 208.6+ KB

In [56]:
columns = ['Time', 'Temperature', 'Humidity', 'Wind', 'Speed', 'Gust',
           'Pressure', 'Precip. Rate.', 'Precip. Accum.','UV', 'Solar']

result = result.dropna(how='all', axis=0, subset=columns,ignore_index=True)

In [57]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1899 entries, 0 to 1898
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Time            1899 non-null   object
 1   Temperature     1899 non-null   object
 2   Dew Point       1899 non-null   object
 3   Humidity        1899 non-null   object
 4   Wind            1892 non-null   object
 5   Speed           1899 non-null   object
 6   Gust            1899 non-null   object
 7   Pressure        1899 non-null   object
 8   Precip. Rate.   1899 non-null   object
 9   Precip. Accum.  1899 non-null   object
 10  UV              1899 non-null   float64
 11  Solar           1899 non-null   object
 12  tab_name        1899 non-null   object
 13  Date            1899 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(12)
memory usage: 207.8+ KB

In [58]:
result.to_csv('donnees/'+ OUTPUT_FILE, encoding='UTF-8', index=False)